spring:
  application:
    name: scoring
  main:
    banner-mode: off

sportsmen-place:
  places:
    1: 10
    2: 9
    3: 8
    4: 7
    5: 6
    6: 5
    7: 4
    8: 3
    9: 2
    10: 1

  official-places:
    1: 5
    2: 4
    3: 3
    4: 2
    5: 1
    6: 1
    7: 1
    8: 1
    9: 1
    10: 1