openapi: 3.0.2
info:
  title: "tournament-storage"
  description: "It's easy to manage your sport tournament or league"
  version: "1.0"
  contact:
    name: "SportManager"
    url: "https://sportmanager.com/support"
    email: "sportmanager@gmail.com"

paths:
  /api/v1/users/score:
    post:
      tags:
        - ScoringService
      operationId: scoreSportsmen
      summary: "Производит скоринг спортсмена по определенному виду спорта"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SportsmenRequestDto"
      responses:
          '200':
            description: ""
            content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/SportsmenResponseDto'
          '400':
            description: "Bad request"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/BadRequest400Dto'
          '401':
            description: "Unauthorized"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Unauthorized401Dto'
          '403':
            description: "Forbidden"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Forbidden403Dto'
          '404':
            description: "Not found"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/NotFound404Dto'
          '500':
            description: "Internal Server Error"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/InternalError500Dto'

components:
  schemas:

    SportsmenRequestDto:
      type: object
      required:
        - sportsmen_id
        - sport
        - period
      properties:
        sportsmen_id:
          type: integer
        sport:
          type: string
        period:
          type: integer

    SportsmenResponseDto:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    SportsmenSanction:
      type: object
      properties:
        sportsmen_id:
          type: integer
        sanction_id:
          type: integer


    BadRequest400Dto:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    Unauthorized401Dto:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    Forbidden403Dto:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    NotFound404Dto:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    InternalError500Dto:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
