build:
  excludeCorrectable: false

formatting:
  active: true
  autoCorrect: true
  FinalNewline:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: true
  MaximumLineLength:
    active: true
    maxLineLength: 150

complexity:
  active: true
  LargeClass:
    active: true
    threshold: 300
  TooManyFunctions:
    active: true
    thresholdInClasses: 15
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false
  LongMethod:
    active: true
    threshold: 50
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
    ignoreDefaultParameters: true

empty-blocks:
  active: true
  EmptyClassBlock:
    active: false
  EmptyFunctionBlock:
    active: false

style:
  active: true
  NewLineAtEndOfFile:
    active: true
  WildcardImport:
    active: true
    excludes: "**/test/**"
  MaxLineLength:
    active: true
    maxLineLength: 150
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 4

performance:
  SpreadOperator:
    active: false

exceptions:
  active: true
  SwallowedException:
    active: false

naming:
  PackageNaming:
    active: true
    excludes: "**/test/**"